### ISSUE TITLE
windows user data is doing uneccessary steps

### ISSUE THREAD

**Issue by adelina-t** [e2e-win/k8s-ovn-ovs#2]
For ansible, why do we need powershell upgrade? I doubt 1803 or even 1709 comes with powershell < 3.0.  https://github.com/e2e-win/k8s-ovn-ovs/blob/master/openstack-scripts/windows-user-data#L5

Also, that's directly copy-paste from ansible website, as I doubt we ever have these credentials :)) https://github.com/e2e-win/k8s-ovn-ovs/blob/master/openstack-scripts/windows-user-data#L7-L8

Why is this needed? https://github.com/e2e-win/k8s-ovn-ovs/blob/master/openstack-scripts/windows-user-data#L15-L18

This hotfix for winrm , why do we need it? As the ansible docs clearly state is for powershell 3.0 . https://github.com/e2e-win/k8s-ovn-ovs/blob/master/openstack-scripts/windows-user-data#L20-L24

**Comment by papagalu** [comment]
solved by #3
